server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  environment: development

services:
  auth:
    # Use service name from docker-compose network
    host: auth-service
    port: 50051
  image:
    host: image-service
    port: 50061
  llm:
    host: llm-service
    port: 50052
  queue:
    host: queue-service
    port: 50053
  agent:
    host: agent-service
    port: 50054
  product_analyzer:
    host: localhost
    port: 50071

jwt:
  secret_key: your-super-secret-jwt-key-change-this-in-production
  access_expiry: 15m
  refresh_expiry: 168h # 7 days

logging:
  level: info
  format: json

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization

# AWS Configuration for S3 and CloudFront
aws:
  region: us-east-1
  s3:
    bucket_name: btk-stox-s3
    region: us-east-1
  cloudfront:
    distribution_id: ${CLOUDFRONT_DISTRIBUTION_ID}
    domain_name: ${CLOUDFRONT_DOMAIN_NAME}
    region: us-east-1
