server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

services:
  auth:
    host: localhost
    port: 50051
  image:
    host: localhost
    port: 8000
  llm:
    host: localhost
    port: 50052
  queue:
    host: localhost
    port: 50053
  agent:
    host: localhost
    port: 50054

logging:
  level: info
  format: json 