// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/proto/product-analyzer/product_analyzer.proto

package product_analyzer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request with image data
type ImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`                                // Image binary data
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                          // Original filename
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type (image/jpeg, image/png, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_analyzer_product_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Request with image URL
type ImageUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // URL to the image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUrlRequest) Reset() {
	*x = ImageUrlRequest{}
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUrlRequest) ProtoMessage() {}

func (x *ImageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUrlRequest.ProtoReflect.Descriptor instead.
func (*ImageUrlRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_analyzer_product_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *ImageUrlRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Response with generated content
type ImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`                             // SEO-optimized product title (max 60 chars)
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                 // SEO-optimized product description (150-300 words)
	SearchInfo    string                 `protobuf:"bytes,3,opt,name=search_info,json=searchInfo,proto3" json:"search_info,omitempty"` // Market research information (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageResponse) Reset() {
	*x = ImageResponse{}
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageResponse) ProtoMessage() {}

func (x *ImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageResponse.ProtoReflect.Descriptor instead.
func (*ImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_analyzer_product_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *ImageResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImageResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImageResponse) GetSearchInfo() string {
	if x != nil {
		return x.SearchInfo
	}
	return ""
}

// Health check messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_analyzer_product_analyzer_proto_rawDescGZIP(), []int{3}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // "healthy" or error message
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"` // Service name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_product_analyzer_product_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_internal_proto_product_analyzer_product_analyzer_proto protoreflect.FileDescriptor

const file_internal_proto_product_analyzer_product_analyzer_proto_rawDesc = "" +
	"\n" +
	"6internal/proto/product-analyzer/product_analyzer.proto\x12\x0fproductanalyzer\"c\n" +
	"\fImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\".\n" +
	"\x0fImageUrlRequest\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\"h\n" +
	"\rImageResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vsearch_info\x18\x03 \x01(\tR\n" +
	"searchInfo\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice2\x99\x02\n" +
	"\x0fProductAnalyzer\x12R\n" +
	"\x11GenerateFromImage\x12\x1d.productanalyzer.ImageRequest\x1a\x1e.productanalyzer.ImageResponse\x12X\n" +
	"\x14GenerateFromImageUrl\x12 .productanalyzer.ImageUrlRequest\x1a\x1e.productanalyzer.ImageResponse\x12X\n" +
	"\vHealthCheck\x12#.productanalyzer.HealthCheckRequest\x1a$.productanalyzer.HealthCheckResponseB.Z,stox-gateway/internal/proto/product-analyzerb\x06proto3"

var (
	file_internal_proto_product_analyzer_product_analyzer_proto_rawDescOnce sync.Once
	file_internal_proto_product_analyzer_product_analyzer_proto_rawDescData []byte
)

func file_internal_proto_product_analyzer_product_analyzer_proto_rawDescGZIP() []byte {
	file_internal_proto_product_analyzer_product_analyzer_proto_rawDescOnce.Do(func() {
		file_internal_proto_product_analyzer_product_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_product_analyzer_product_analyzer_proto_rawDesc), len(file_internal_proto_product_analyzer_product_analyzer_proto_rawDesc)))
	})
	return file_internal_proto_product_analyzer_product_analyzer_proto_rawDescData
}

var file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_product_analyzer_product_analyzer_proto_goTypes = []any{
	(*ImageRequest)(nil),        // 0: productanalyzer.ImageRequest
	(*ImageUrlRequest)(nil),     // 1: productanalyzer.ImageUrlRequest
	(*ImageResponse)(nil),       // 2: productanalyzer.ImageResponse
	(*HealthCheckRequest)(nil),  // 3: productanalyzer.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 4: productanalyzer.HealthCheckResponse
}
var file_internal_proto_product_analyzer_product_analyzer_proto_depIdxs = []int32{
	0, // 0: productanalyzer.ProductAnalyzer.GenerateFromImage:input_type -> productanalyzer.ImageRequest
	1, // 1: productanalyzer.ProductAnalyzer.GenerateFromImageUrl:input_type -> productanalyzer.ImageUrlRequest
	3, // 2: productanalyzer.ProductAnalyzer.HealthCheck:input_type -> productanalyzer.HealthCheckRequest
	2, // 3: productanalyzer.ProductAnalyzer.GenerateFromImage:output_type -> productanalyzer.ImageResponse
	2, // 4: productanalyzer.ProductAnalyzer.GenerateFromImageUrl:output_type -> productanalyzer.ImageResponse
	4, // 5: productanalyzer.ProductAnalyzer.HealthCheck:output_type -> productanalyzer.HealthCheckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_product_analyzer_product_analyzer_proto_init() }
func file_internal_proto_product_analyzer_product_analyzer_proto_init() {
	if File_internal_proto_product_analyzer_product_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_product_analyzer_product_analyzer_proto_rawDesc), len(file_internal_proto_product_analyzer_product_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_product_analyzer_product_analyzer_proto_goTypes,
		DependencyIndexes: file_internal_proto_product_analyzer_product_analyzer_proto_depIdxs,
		MessageInfos:      file_internal_proto_product_analyzer_product_analyzer_proto_msgTypes,
	}.Build()
	File_internal_proto_product_analyzer_product_analyzer_proto = out.File
	file_internal_proto_product_analyzer_product_analyzer_proto_goTypes = nil
	file_internal_proto_product_analyzer_product_analyzer_proto_depIdxs = nil
}
